spring:
   application:
      name: ATM_Service
   datasource:
      url: jdbc:mysql://localhost:3306/ATMsystem
      username: root
      password: Sakshibele@03
   jpa:
      show-sql: true
      format-sql: true
      hibernate:
         ddl-auto: update
   mvc:
      view:
         prefix: /views/
         suffix: .jsp
   
      
      
